---
- name: the palybook is to install the package of httpd
  hosts: all
  become: true
  tasks:
  - name: installing package of httpd
    yum:
      name: httpd
      state: latest

  - name: start a service
    service:
      name: httpd
      state: started 
